stacks:
  local:
    RABBITMQ_HOST: localhost
    RABBITMQ_USERNAME: swisscon
    RABBITMQ_PASSWORD: swisscon
    MONOLITH_SERVICE_BASE: 'http://localhost:8080'
    TAG: '0.1.0-local'
    MEDIA_WIDGET_V2: 'off'
    MEDIA_WIDGET_V2_CUT_OFF_PROJECT_ID: '999999'
  localk8:
    RABBITMQ_HOST: rabbitmq-service
    RABBITMQ_USERNAME: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJwcml2YXRlIiwic3ViIjoiYXBpLXNlcnZpY2UiLCJpc3MiOiJzYy1zZWN1cml0eS5sb2NhbGs4IiwiZXhwIjoxOTExMzcyMTA5fQ.REoOXEhvZDaxfS3FdYF9w1arW2sK4jCCvc0kSOyauak
    RABBITMQ_PASSWORD: ignored
    MONOLITH_SERVICE_BASE: 'http://api-service:8080'
    MEDIA_WIDGET_V2: 'off'
    MEDIA_WIDGET_V2_CUT_OFF_PROJECT_ID: '999999'
  dev:
    RABBITMQ_HOST: rabbitmq-service
    RABBITMQ_PASSWORD: ignored
    MONOLITH_SERVICE_BASE: 'http://api-service:8080'
    MEDIA_WIDGET_V2: 'off'
    MEDIA_WIDGET_V2_CUT_OFF_PROJECT_ID: '999999'
  stage:
    RABBITMQ_HOST: rabbitmq-service
    RABBITMQ_PASSWORD: ignored
    MONOLITH_SERVICE_BASE: 'http://api-service:8080'
    MEDIA_WIDGET_V2: 'off'
    MEDIA_WIDGET_V2_CUT_OFF_PROJECT_ID: '999999'
  prod:
    RABBITMQ_HOST: rabbitmq-service
    RABBITMQ_PASSWORD: ignored
    MONOLITH_SERVICE_BASE: 'http://api-service:8080'
    MEDIA_WIDGET_V2: 'off'
    MEDIA_WIDGET_V2_CUT_OFF_PROJECT_ID: '999999'
