aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/966/ s3://sc-dev-private-storage/StorageUrl/103
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/967/ s3://sc-dev-private-storage/StorageUrl/104
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/968/ s3://sc-dev-private-storage/StorageUrl/105
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/969/ s3://sc-dev-private-storage/StorageUrl/106
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/970/ s3://sc-dev-private-storage/StorageUrl/107
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/971/ s3://sc-dev-private-storage/StorageUrl/108
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/972/ s3://sc-dev-private-storage/StorageUrl/109
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/973/ s3://sc-dev-private-storage/StorageUrl/110
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/974/ s3://sc-dev-private-storage/StorageUrl/111
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/975/ s3://sc-dev-private-storage/StorageUrl/112
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/976/ s3://sc-dev-private-storage/StorageUrl/113
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/977/ s3://sc-dev-private-storage/StorageUrl/114
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/978/ s3://sc-dev-private-storage/StorageUrl/115
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/979/ s3://sc-dev-private-storage/StorageUrl/116
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/980/ s3://sc-dev-private-storage/StorageUrl/117
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/981/ s3://sc-dev-private-storage/StorageUrl/118
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/982/ s3://sc-dev-private-storage/StorageUrl/119
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/983/ s3://sc-dev-private-storage/StorageUrl/120
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/984/ s3://sc-dev-private-storage/StorageUrl/121
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/985/ s3://sc-dev-private-storage/StorageUrl/122
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/986/ s3://sc-dev-private-storage/StorageUrl/123
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/987/ s3://sc-dev-private-storage/StorageUrl/124
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/988/ s3://sc-dev-private-storage/StorageUrl/125
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/989/ s3://sc-dev-private-storage/StorageUrl/126
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/990/ s3://sc-dev-private-storage/StorageUrl/127
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/991/ s3://sc-dev-private-storage/StorageUrl/128
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/992/ s3://sc-dev-private-storage/StorageUrl/129
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/993/ s3://sc-dev-private-storage/StorageUrl/130
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/994/ s3://sc-dev-private-storage/StorageUrl/131
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/995/ s3://sc-dev-private-storage/StorageUrl/132
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/996/ s3://sc-dev-private-storage/StorageUrl/133
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/997/ s3://sc-dev-private-storage/StorageUrl/134
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/998/ s3://sc-dev-private-storage/StorageUrl/135
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/999/ s3://sc-dev-private-storage/StorageUrl/136
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1000/ s3://sc-dev-private-storage/StorageUrl/137
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1001/ s3://sc-dev-private-storage/StorageUrl/138
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1002/ s3://sc-dev-private-storage/StorageUrl/139
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1003/ s3://sc-dev-private-storage/StorageUrl/140
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1004/ s3://sc-dev-private-storage/StorageUrl/141
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1005/ s3://sc-dev-private-storage/StorageUrl/142
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1006/ s3://sc-dev-private-storage/StorageUrl/143
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1007/ s3://sc-dev-private-storage/StorageUrl/144
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1008/ s3://sc-dev-private-storage/StorageUrl/145
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1009/ s3://sc-dev-private-storage/StorageUrl/146
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1010/ s3://sc-dev-private-storage/StorageUrl/147
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1011/ s3://sc-dev-private-storage/StorageUrl/148
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1012/ s3://sc-dev-private-storage/StorageUrl/149
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1013/ s3://sc-dev-private-storage/StorageUrl/150
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1014/ s3://sc-dev-private-storage/StorageUrl/151
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1015/ s3://sc-dev-private-storage/StorageUrl/152
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1016/ s3://sc-dev-private-storage/StorageUrl/153
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1017/ s3://sc-dev-private-storage/StorageUrl/154
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1018/ s3://sc-dev-private-storage/StorageUrl/155
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1019/ s3://sc-dev-private-storage/StorageUrl/156
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1020/ s3://sc-dev-private-storage/StorageUrl/157
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1021/ s3://sc-dev-private-storage/StorageUrl/158
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1022/ s3://sc-dev-private-storage/StorageUrl/159
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1023/ s3://sc-dev-private-storage/StorageUrl/160
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1024/ s3://sc-dev-private-storage/StorageUrl/161
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1025/ s3://sc-dev-private-storage/StorageUrl/162
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1026/ s3://sc-dev-private-storage/StorageUrl/163
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1027/ s3://sc-dev-private-storage/StorageUrl/164
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1028/ s3://sc-dev-private-storage/StorageUrl/165
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1029/ s3://sc-dev-private-storage/StorageUrl/166
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1030/ s3://sc-dev-private-storage/StorageUrl/167
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1031/ s3://sc-dev-private-storage/StorageUrl/168
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1032/ s3://sc-dev-private-storage/StorageUrl/169
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1033/ s3://sc-dev-private-storage/StorageUrl/170
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1034/ s3://sc-dev-private-storage/StorageUrl/171
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1035/ s3://sc-dev-private-storage/StorageUrl/172
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1036/ s3://sc-dev-private-storage/StorageUrl/173
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1037/ s3://sc-dev-private-storage/StorageUrl/174
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1038/ s3://sc-dev-private-storage/StorageUrl/175
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1039/ s3://sc-dev-private-storage/StorageUrl/176
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1040/ s3://sc-dev-private-storage/StorageUrl/177
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1041/ s3://sc-dev-private-storage/StorageUrl/178
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1042/ s3://sc-dev-private-storage/StorageUrl/179
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1043/ s3://sc-dev-private-storage/StorageUrl/180
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1044/ s3://sc-dev-private-storage/StorageUrl/181
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1045/ s3://sc-dev-private-storage/StorageUrl/182
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1046/ s3://sc-dev-private-storage/StorageUrl/183
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1047/ s3://sc-dev-private-storage/StorageUrl/184
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1048/ s3://sc-dev-private-storage/StorageUrl/185
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1049/ s3://sc-dev-private-storage/StorageUrl/186
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1050/ s3://sc-dev-private-storage/StorageUrl/187
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1051/ s3://sc-dev-private-storage/StorageUrl/188
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1052/ s3://sc-dev-private-storage/StorageUrl/189
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1053/ s3://sc-dev-private-storage/StorageUrl/190
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1054/ s3://sc-dev-private-storage/StorageUrl/191
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1055/ s3://sc-dev-private-storage/StorageUrl/192
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1056/ s3://sc-dev-private-storage/StorageUrl/193
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1057/ s3://sc-dev-private-storage/StorageUrl/194
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1058/ s3://sc-dev-private-storage/StorageUrl/195
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1059/ s3://sc-dev-private-storage/StorageUrl/196
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1060/ s3://sc-dev-private-storage/StorageUrl/197
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1061/ s3://sc-dev-private-storage/StorageUrl/198
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1062/ s3://sc-dev-private-storage/StorageUrl/199
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1063/ s3://sc-dev-private-storage/StorageUrl/200
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1064/ s3://sc-dev-private-storage/StorageUrl/201
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1065/ s3://sc-dev-private-storage/StorageUrl/202
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1066/ s3://sc-dev-private-storage/StorageUrl/203
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1067/ s3://sc-dev-private-storage/StorageUrl/204
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1068/ s3://sc-dev-private-storage/StorageUrl/205
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1069/ s3://sc-dev-private-storage/StorageUrl/206
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1070/ s3://sc-dev-private-storage/StorageUrl/207
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1071/ s3://sc-dev-private-storage/StorageUrl/208
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1072/ s3://sc-dev-private-storage/StorageUrl/209
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1073/ s3://sc-dev-private-storage/StorageUrl/210
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1074/ s3://sc-dev-private-storage/StorageUrl/211
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1075/ s3://sc-dev-private-storage/StorageUrl/212
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1076/ s3://sc-dev-private-storage/StorageUrl/213
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1077/ s3://sc-dev-private-storage/StorageUrl/214
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1078/ s3://sc-dev-private-storage/StorageUrl/215
aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/StorageUrl/1079/ s3://sc-dev-private-storage/StorageUrl/216

aws s3 --profile siryus --recursive mv s3://sc-dev-private-storage/1821-4022019-122921-397390/ s3://sc-dev-private-storage/StorageUrl/958/url

